name: Generate Growing Snake

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Generate growing snake
      - name: Generate growing snake
        uses: Platane/snk@v3
        with:
          github_user_name: anugrahk21
          outputs: |
            dist/growing-snake.svg
            dist/growing-snake-dark.svg?palette=github-dark
            dist/growing-snake.gif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Generate additional snake variants
      - name: Generate snake variants
        uses: Platane/snk@v3
        with:
          github_user_name: anugrahk21
          outputs: |
            dist/snake-variant.svg
            dist/snake-dark-variant.svg?palette=github-dark&color_snake=#ff6b6b&color_dots=#c3f7f5,#96f2d7,#51cf66,#40c057,#37b24d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy all generated files
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}