name: Generate Growing Snake

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Generate growing snake
      - name: Generate growing snake
        uses: Platane/snk@v3
        with:
          github_user_name: anugrahk21
          outputs: |
            dist/growing-snake.svg
            dist/growing-snake-dark.svg?palette=github-dark
            dist/growing-snake.gif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Custom snake with growing effect
      - name: Generate custom growing snake
        run: |
          # Create a custom SVG that simulates growing snake
          mkdir -p dist
          cat > dist/custom-growing-snake.svg << 'EOF'
          <svg viewBox="0 0 900 200" xmlns="http://www.w3.org/2000/svg">
            <style>
              .snake-segment { 
                animation: grow 3s infinite linear;
                fill: #7c3aed;
              }
              .contribution { 
                fill: #22c55e; 
                animation: eaten 0.5s ease-in-out forwards;
              }
              @keyframes grow {
                0% { opacity: 0; transform: scale(0); }
                50% { opacity: 1; transform: scale(1); }
                100% { opacity: 1; transform: scale(1); }
              }
              @keyframes eaten {
                0% { fill: #22c55e; transform: scale(1); }
                50% { fill: #f59e0b; transform: scale(1.2); }
                100% { fill: #7c3aed; transform: scale(1); }
              }
            </style>
            
            <!-- Snake segments that grow over time -->
            <rect class="snake-segment" x="10" y="80" width="12" height="12" rx="2" style="animation-delay: 0s;"/>
            <rect class="snake-segment" x="25" y="80" width="12" height="12" rx="2" style="animation-delay: 0.2s;"/>
            <rect class="snake-segment" x="40" y="80" width="12" height="12" rx="2" style="animation-delay: 0.4s;"/>
            <rect class="snake-segment" x="55" y="80" width="12" height="12" rx="2" style="animation-delay: 0.6s;"/>
            <rect class="snake-segment" x="70" y="80" width="12" height="12" rx="2" style="animation-delay: 0.8s;"/>
            <rect class="snake-segment" x="85" y="80" width="12" height="12" rx="2" style="animation-delay: 1.0s;"/>
            <rect class="snake-segment" x="100" y="80" width="12" height="12" rx="2" style="animation-delay: 1.2s;"/>
            <rect class="snake-segment" x="115" y="80" width="12" height="12" rx="2" style="animation-delay: 1.4s;"/>
            
            <!-- Contributions being eaten -->
            <rect class="contribution" x="130" y="80" width="12" height="12" rx="2" style="animation-delay: 1.6s;"/>
            <rect class="contribution" x="145" y="80" width="12" height="12" rx="2" style="animation-delay: 1.8s;"/>
            <rect class="contribution" x="160" y="80" width="12" height="12" rx="2" style="animation-delay: 2.0s;"/>
            
            <!-- Text -->
            <text x="10" y="120" font-family="Arial, sans-serif" font-size="14" fill="#374151">
              🐍 Contribution Snake - Growing with each commit!
            </text>
          </svg>
          EOF

      # Deploy all generated files
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}